packages:
  - '.'
  - 'cli'
  - 'prototypes/*'

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - unrs-resolver

onlyBuiltDependencies:
  - sharp@0.34.5
  - simple-git-hooks@2.13.1

ignoreWorkspaceRootCheck: true
