import type { SWType } from '@composable-vite-pwa/workbox-build/types'
import type { VitePWAStrategy } from '@composable-vite-pwa/unplugin-pwa/node/types'
import type { PwaModuleOptions } from '@composable-vite-pwa/nuxt'
import process from 'node:process'
import { isDevelopment } from 'std-env'

function defineConfig<
  UserStrategy extends VitePWAStrategy = 'generate-sw',
  T extends SWType = 'classic',
>(options: PwaModuleOptions<UserStrategy, T>) {
  return options
}

export default defineConfig({
  disable: isDevelopment && process.env.VITE_DEV_PWA !== 'true',
  swType: 'classic-and-module',
  strategies: 'build-sw',
  base: '/',
  scope: '/',
  minify: !(isDevelopment && process.env.VITE_DEV_PWA === 'true'),
  registerType: 'prompt',
  client: {
    // Check for updates every hour
    periodicSyncForUpdates: 3_600,
    installPrompt: true,
  },
  registerWebManifestInRouteRules: true,
  experimental: {
    enableWorkboxPayloadQueryParams: true,
  },
  devOptions: {
    enabled: process.env.VITE_DEV_PWA === 'true',
    type: 'module',
    inspector: 'standalone',
    suppressWarnings: true,
    navigateFallback: '/',
  },
  buildSW: {
    swSrc: '~~/service-worker/npmx-sw.ts',
    sourcemap: isDevelopment && process.env.VITE_DEV_PWA === 'true',
    globPatterns: [
      '**/*.{js,css,html,txt,svg,png,ico,webp,woff,woff2,ttf,eot,otf,wasm,webmanifest}',
    ],
  },
  manifest: {
    name: 'npmx',
    short_name: 'npmx',
    description: 'A fast, modern browser for the npm registry',
    theme_color: '#0a0a0a',
    background_color: '#0a0a0a',
    display: 'standalone',
    display_override: ['window-controls-overlay', 'standalone'],
    id: '/',
    start_url: '/',
    shortcuts: [
      {
        name: 'Search packages',
        short_name: 'Search',
        description: 'Search the npm registry',
        url: '/search',
        icons: [{ src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' }],
      },
      {
        name: 'Compare packages',
        short_name: 'Compare',
        description: 'Compare npm packages side by side',
        url: '/compare',
        icons: [{ src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' }],
      },
      {
        name: 'Settings',
        short_name: 'Settings',
        description: 'Customize your npmx experience',
        url: '/settings',
        icons: [{ src: 'pwa-192x192.png', sizes: '192x192', type: 'image/png' }],
      },
    ],
    // Richer install UI — https://developer.chrome.com/blog/richer-install-ui-desktop
    // Generated by `pnpm generate:screenshots` (scripts/generate-pwa-screenshots.ts).
    // Commit the output PNGs so Vercel CI picks them up on the next build.
    screenshots: [
      // Desktop (form_factor "wide") — shown in Chrome's install dialog on desktop
      {
        src: 'screenshots/desktop-dark-home.png',
        sizes: '1280x800',
        type: 'image/png',
        form_factor: 'wide',
        label: 'Browse npm packages',
      },
      {
        src: 'screenshots/desktop-light-home.png',
        sizes: '1280x800',
        type: 'image/png',
        form_factor: 'wide',
        label: 'Browse npm packages (light mode)',
      },
      {
        src: 'screenshots/desktop-dark-package.png',
        sizes: '1280x800',
        type: 'image/png',
        form_factor: 'wide',
        label: 'View package details',
      },
      {
        src: 'screenshots/desktop-light-package.png',
        sizes: '1280x800',
        type: 'image/png',
        form_factor: 'wide',
        label: 'View package details (light mode)',
      },
      // Mobile (form_factor "narrow") — shown in Chrome's install dialog on Android
      {
        src: 'screenshots/mobile-dark-home.png',
        sizes: '390x844',
        type: 'image/png',
        form_factor: 'narrow',
        label: 'Browse npm packages',
      },
      {
        src: 'screenshots/mobile-light-home.png',
        sizes: '390x844',
        type: 'image/png',
        form_factor: 'narrow',
        label: 'Browse npm packages (light mode)',
      },
      {
        src: 'screenshots/mobile-dark-package.png',
        sizes: '390x844',
        type: 'image/png',
        form_factor: 'narrow',
        label: 'View package details',
      },
      {
        src: 'screenshots/mobile-light-package.png',
        sizes: '390x844',
        type: 'image/png',
        form_factor: 'narrow',
        label: 'View package details (light mode)',
      },
    ] as {
      src: string
      sizes: string
      type: string
      form_factor: 'wide' | 'narrow'
      label: string
    }[],
    icons: [
      {
        src: 'pwa-64x64.png',
        sizes: '64x64',
        type: 'image/png',
      },
      {
        src: 'pwa-192x192.png',
        sizes: '192x192',
        type: 'image/png',
      },
      {
        src: 'pwa-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'any',
      },
      {
        src: 'maskable-icon-512x512.png',
        sizes: '512x512',
        type: 'image/png',
        purpose: 'maskable',
      },
    ],
  },
})
