name: "\U0001F41E Bug report"
description: Create a report to help us improve Npmx
body:
  - type: markdown
    attributes:
      value: |
        Please carefully read the contribution docs before creating a bug report
        👉 https://github.com/npmx-dev/npmx.dev/blob/main/CONTRIBUTING.md
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is. If you intend to submit a PR for this issue, tell us in the description. Thanks!
      placeholder: Bug description
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: If applicable, add any other context about the problem here
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        Optional if you have reproduction steps. Please try not to insert an image but copy paste the log text.
      render: shell-script
