/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'blue.microcosm.links.getBacklinks'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  subject: /*#__PURE__*/ l.string({ format: 'uri' }),
  source: /*#__PURE__*/ l.string(),
  did: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'did' })),
  ),
  limit: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.integer({ minimum: 1, maximum: 100 }),
      16,
    ),
  ),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  total: /*#__PURE__*/ l.integer(),
  records: /*#__PURE__*/ l.array(
    /*#__PURE__*/ l.ref<LinkRecord>((() => linkRecord) as any),
  ),
  cursor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Constellation: list records linking to any record, identity, or uri */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid

/** a record linking to the subject */
type LinkRecord = {
  $type?: 'blue.microcosm.links.getBacklinks#linkRecord'

  /**
   * the DID of the linking record's repository
   */
  did: l.DidString

  /**
   * the collection of the linking record
   */
  collection: l.NsidString

  /**
   * the record key of the linking record
   */
  rkey: l.RecordKeyString
}

export type { LinkRecord }

/** a record linking to the subject */
const linkRecord = /*#__PURE__*/ l.typedObject<LinkRecord>(
  $nsid,
  'linkRecord',
  /*#__PURE__*/ l.object({
    did: /*#__PURE__*/ l.string({ format: 'did' }),
    collection: /*#__PURE__*/ l.string({ format: 'nsid' }),
    rkey: /*#__PURE__*/ l.string({ format: 'record-key' }),
  }),
)

export { linkRecord }
