/*
 * THIS FILE WAS GENERATED BY "@atproto/lex". DO NOT EDIT.
 */

import { l } from '@atproto/lex'

const $nsid = 'blue.microcosm.links.getManyToManyCounts'

export { $nsid }

export const $params = /*#__PURE__*/ l.params({
  subject: /*#__PURE__*/ l.string({ format: 'uri' }),
  source: /*#__PURE__*/ l.string(),
  pathToOther: /*#__PURE__*/ l.string(),
  did: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(/*#__PURE__*/ l.string({ format: 'did' })),
  ),
  otherSubject: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.array(/*#__PURE__*/ l.string()),
  ),
  limit: /*#__PURE__*/ l.optional(
    /*#__PURE__*/ l.withDefault(
      /*#__PURE__*/ l.integer({ minimum: 1, maximum: 100 }),
      16,
    ),
  ),
})

export type $Params = l.InferOutput<typeof $params>

export const $output = /*#__PURE__*/ l.jsonPayload({
  counts_by_other_subject: /*#__PURE__*/ l.array(
    /*#__PURE__*/ l.ref<CountBySubject>((() => countBySubject) as any),
  ),
  cursor: /*#__PURE__*/ l.optional(/*#__PURE__*/ l.string()),
})

export type $Output<B = l.BinaryData> = l.InferPayload<typeof $output, B>
export type $OutputBody<B = l.BinaryData> = l.InferPayloadBody<
  typeof $output,
  B
>

/** Constellation: count many-to-many relationships with secondary link paths */
const main = /*#__PURE__*/ l.query($nsid, $params, $output)

export { main }

export const $lxm = $nsid

/** count of links to a secondary subject */
type CountBySubject = {
  $type?: 'blue.microcosm.links.getManyToManyCounts#countBySubject'

  /**
   * the secondary subject being counted
   */
  subject: string

  /**
   * total number of links to this subject
   */
  total: number

  /**
   * number of distinct DIDs linking to this subject
   */
  distinct: number
}

export type { CountBySubject }

/** count of links to a secondary subject */
const countBySubject = /*#__PURE__*/ l.typedObject<CountBySubject>(
  $nsid,
  'countBySubject',
  /*#__PURE__*/ l.object({
    subject: /*#__PURE__*/ l.string(),
    total: /*#__PURE__*/ l.integer(),
    distinct: /*#__PURE__*/ l.integer(),
  }),
)

export { countBySubject }
