export const BADGE_TYPES = Object.freeze([
  'version',
  'license',
  'size',
  'downloads',
  'downloads-day',
  'downloads-week',
  'downloads-month',
  'downloads-year',
  'vulnerabilities',
  'dependencies',
  'created',
  'updated',
  'engines',
  'types',
  'maintainers',
  'deprecated',
  'quality',
  'popularity',
  'maintenance',
  'score',
  'name',
] as const)
