on:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  deploy-canary:
    if: github.repository == 'npmx-dev/npmx.dev'
    name: 🚀 Deploy to canary (main.npmx.dev)
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
      - run: npx vercel deploy --target=canary --token="$VERCEL_TOKEN"
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
