name: i18n-meta

on:
  push:
    branches:
      - main
    paths:
      - 'i18n/locales/en.json'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  update:
    name: 🌐 Update en.meta.json
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write # commit and push updated i18n metadata

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          fetch-depth: 2
          persist-credentials: false

      - uses: voidzero-dev/setup-vp@ca1c46663915d6c1042ae23bd39ab85718bfb0fa # v1.10.0
        with:
          node-version: lts/*
          run-install: false

      - name: 📦 Install dependencies
        run: vp install

      - name: 🌐 Update i18n metadata
        run: vp run i18n:meta:update-en-meta

      - name: ⬆︎ Commit and Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add i18n/locales/en.meta.json
          if ! git diff --cached --quiet; then
            git commit -m 'chore(i18n): update `en.meta.json` [skip ci]'
            git push
          else
            echo "No changes in en.meta.json, skipping commit."
          fi
