name: Welcome

on:
  pull_request_target:
    branches: [main]
    types: [opened]

permissions:
  pull-requests: write

jobs:
  greeting:
    name: Greet First-Time Contributors
    if: github.repository == 'npmx-dev/npmx.dev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/first-interaction@1c4688942c71f71d4f5502a26ea67c331730fa4d # v3.1.0
        with:
          pr_message: |
            Thanks for your first contribution, @${{ github.event.pull_request.user.login }}! 🚀

            We'd love to welcome you to the npmx community. While you wait for a review, come and say hi on [Discord](https://chat.npmx.dev)!

            Once your pull request is merged, you'll be able to visit [npmx.wamellow.com](https://npmx.wamellow.com/) to claim your **contributor** role. 🚀
